[package]
name = "kishmat-tooling"
version = "1.0.0"
edition = "2024"
authors = ["Ahmad Hamdi Emara"]
description = "Trait-based developer tooling for KishMat recipes"
license = "MIT"

[[bin]]
name = "kishmat-tooling"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6", features = ["derive"] }
kishmat-updater = { path = "../kishmat-updater" }
dirs = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
types = { package = "kishmat-types", path = "../kishmat-types" }
search = { package = "kishmat-search", path = "../kishmat-search" }
