[package]
name = "mujrim-search"
version = "2.0.0"
edition = "2024"
authors = ["Ahmad Hamdi Emara"]
description = "Search engine for the Mujrim chess engine"
license = "MIT"

[features]
default = ["book", "nnue"]
book = []
nnue = ["eval/nnue"]

[dependencies]
types = { package = "mujrim-types", path = "../mujrim-types" }
eval = { package = "mujrim-eval", path = "../mujrim-eval", default-features = false, features = ["nnue", "simd", "akimbo-nnue", "stockfish-nnue", "reckless-nnue", "embedded-networks"] }
toml = "0.8"
sha2 = "0.10"
