[package]
name = "kishmat-search"
version = "1.0.0"
edition = "2024"
authors = ["Ahmad Hamdi Emara"]
description = "Search engine for the Kishmat chess engine"
license = "MIT"

[features]
default = ["book", "nnue"]
book = []
nnue = ["eval/nnue"]

[dependencies]
types = { package = "kishmat-types", path = "../kishmat-types" }
eval = { package = "kishmat-eval", path = "../kishmat-eval" }
toml = "0.8"