[package]
name = "mujrim-ui"
version = "2.0.0"
edition = "2024"
authors = ["Ahmad Hamdi Emara"]
description = "GUI for the Mujrim chess engine using iced"
license = "MIT"

[features]
default = ["book", "nnue"]
book = ["search/book"]
nnue = ["search/nnue"]

[[bin]]
name = "mujrim-ui"
path = "src/main.rs"

[dependencies]
iced = { version = "0.14", features = ["canvas", "image", "svg", "tokio"] }
iced_fonts = { version = "0.3", features = ["lucide"] }
types = { package = "mujrim-types", path = "../mujrim-types" }
search = { package = "mujrim-search", path = "../mujrim-search" }
eval = { package = "mujrim-eval", path = "../mujrim-eval" }
rfd = "0.15"
image = "0.25"
rand = "0.9"
arboard = "3.6.1"
rodio = "0.20"
gif = "0.13"
xcap = "0.9"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
dirs = "6"
updater = { package = "mujrim-updater", path = "../mujrim-updater" }
mujrim-protocols = { path = "../mujrim-protocols" }
mujrim-study = { path = "../mujrim-study" }
mujrim-benchmarker = { path = "../mujrim-benchmarker", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
