[package]
name = "mujrim-comms"
version = "1.0.0"
edition = "2024"
authors = ["Ahmad Hamdi Emara"]
description = "UCI and XBoard protocol handlers for the Mujrim engine"
license = "MIT"

[features]
default = ["xboard", "book", "nnue", "reckless-nnue", "stockfish-nnue", "viridithas-nnue", "obsidian-nnue", "syzygy"]
xboard = []
book = ["search/book"]
nnue = ["search/nnue"]
reckless-nnue = ["eval/reckless-nnue", "search/reckless-nnue"]
stockfish-nnue = ["eval/stockfish-nnue", "search/stockfish-nnue"]
viridithas-nnue = ["eval/viridithas-nnue", "search/viridithas-nnue"]
obsidian-nnue = ["eval/obsidian-nnue", "search/obsidian-nnue"]
syzygy = ["search/syzygy"]

[dependencies]
types = { package = "mujrim-types", path = "../mujrim-types" }
search = { package = "mujrim-search", path = "../mujrim-search", default-features = false }
eval = { package = "mujrim-eval", path = "../mujrim-eval", default-features = false }
