[package]
name = "kishmat-ui"
version = "2.0.0"
edition = "2024"
authors = ["Ahmad Hamdi Emara"]
description = "GUI for the Kishmat chess engine using iced"
license = "MIT"

[features]
default = ["book", "nnue"]
book = ["search/book"]
nnue = ["search/nnue"]

[[bin]]
name = "kishmat-ui"
path = "src/main.rs"

[dependencies]
iced = { version = "0.14", features = ["canvas", "image", "tokio"] }
types = { package = "kishmat-types", path = "../kishmat-types" }
search = { package = "kishmat-search", path = "../kishmat-search" }
eval = { package = "kishmat-eval", path = "../kishmat-eval" }
rfd = "0.15"
image = "0.25"
rand = "0.9"
arboard = "3.6.1"
rodio = "0.20"
gif = "0.13"
xcap = "0.9"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
dirs = "6"
updater = { package = "kishmat-updater", path = "../kishmat-updater" }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
