[package]
name = "kishmat-tests"
version = "2.0.0"
edition = "2024"
authors = ["Ahmad Hamdi Emara"]
description = "Integration tests for the Kishmat chess engine"
license = "MIT"

[dependencies]
types = { package = "kishmat-types", path = "../kishmat-types" }
search = { package = "kishmat-search", path = "../kishmat-search" }
eval = { package = "kishmat-eval", path = "../kishmat-eval" }
comms = { package = "kishmat-comms", path = "../kishmat-comms" }
