[package]
name = "kishmat-comms"
version = "2.0.0"
edition = "2024"
authors = ["Ahmad Hamdi Emara"]
description = "UCI and XBoard protocol handlers for the Kishmat engine"
license = "MIT"

[features]
default = ["xboard", "book", "nnue"]
xboard = []
book = ["search/book"]
nnue = ["search/nnue"]

[dependencies]
types = { package = "kishmat-types", path = "../kishmat-types" }
search = { package = "kishmat-search", path = "../kishmat-search" }
eval = { package = "kishmat-eval", path = "../kishmat-eval" }
