//! Audio engine for chess sound effects.
//!
//! Uses `rodio` with procedurally generated WAV sounds for moves and captures.
//! Sounds are embedded as generated byte arrays — no external files needed.

use std::io::Cursor;

/// Holds the audio output stream and provides methods to play sound effects.
pub struct SoundEngine {
    _stream: rodio::OutputStream,
    stream_handle: rodio::OutputStreamHandle,
    move_sound: Vec<u8>,
    capture_sound: Vec<u8>,
}

impl SoundEngine {
    /// Initialize the audio engine. Returns `None` if audio device is unavailable.
    pub fn new() -> Option<Self> {
        let (stream, stream_handle) = rodio::OutputStream::try_default().ok()?;
        Some(Self {
            _stream: stream,
            stream_handle,
            move_sound: generate_move_wav(),
            capture_sound: generate_capture_wav(),
        })
    }

    /// Play the "piece moved" sound (soft wooden tap).
    pub fn play_move(&self) {
        if let Ok(source) = rodio::Decoder::new(Cursor::new(self.move_sound.clone())) {
            let _ = self.stream_handle.play_raw(
                rodio::source::Source::convert_samples(source),
            );
        }
    }

    /// Play the "piece captured" sound (sharper click).
    pub fn play_capture(&self) {
        if let Ok(source) = rodio::Decoder::new(Cursor::new(self.capture_sound.clone())) {
            let _ = self.stream_handle.play_raw(
                rodio::source::Source::convert_samples(source),
            );
        }
    }
}

// ── Procedural WAV generation ───────────────────────────────────
// Generate short ~100ms WAV samples as byte arrays.

fn generate_move_wav() -> Vec<u8> {
    // Soft wooden tap: 80ms sine wave at 400Hz with fast exponential decay
    let sample_rate = 44100u32;
    let duration_ms = 80;
    let num_samples = (sample_rate as usize * duration_ms) / 1000;
    let mut samples = Vec::with_capacity(num_samples);

    for i in 0..num_samples {
        let t = i as f64 / sample_rate as f64;
        // Main tone: 400Hz sine
        let tone = (2.0 * std::f64::consts::PI * 400.0 * t).sin();
        // Second harmonic for body
        let tone2 = (2.0 * std::f64::consts::PI * 800.0 * t).sin() * 0.3;
        // Fast exponential decay (tau = 0.015s)
        let envelope = (-t / 0.015).exp();
        let sample = ((tone + tone2) * envelope * 0.6 * 32767.0) as i16;
        samples.push(sample);
    }

    encode_wav(&samples, sample_rate)
}

fn generate_capture_wav() -> Vec<u8> {
    // Sharper click: 100ms with higher frequency and noise burst
    let sample_rate = 44100u32;
    let duration_ms = 100;
    let num_samples = (sample_rate as usize * duration_ms) / 1000;
    let mut samples = Vec::with_capacity(num_samples);

    // Simple LCG for deterministic pseudo-random noise
    let mut rng_state: u32 = 12345;

    for i in 0..num_samples {
        let t = i as f64 / sample_rate as f64;
        // Higher frequency click: 600Hz + 1200Hz
        let tone = (2.0 * std::f64::consts::PI * 600.0 * t).sin();
        let tone2 = (2.0 * std::f64::consts::PI * 1200.0 * t).sin() * 0.4;
        // Noise burst for "impact" feel (first 10ms only)
        let noise = if t < 0.010 {
            rng_state = rng_state.wrapping_mul(1103515245).wrapping_add(12345);
            ((rng_state >> 16) as f64 / 32768.0 - 1.0) * 0.5
        } else {
            0.0
        };
        // Sharper decay (tau = 0.012s)
        let envelope = (-t / 0.012).exp();
        let sample = ((tone + tone2 + noise) * envelope * 0.7 * 32767.0) as i16;
        samples.push(sample);
    }

    encode_wav(&samples, sample_rate)
}

/// Encode 16-bit mono PCM samples as a WAV byte array.
fn encode_wav(samples: &[i16], sample_rate: u32) -> Vec<u8> {
    let data_size = (samples.len() * 2) as u32;
    let file_size = 36 + data_size;

    let mut wav = Vec::with_capacity(44 + data_size as usize);

    // RIFF header
    wav.extend_from_slice(b"RIFF");
    wav.extend_from_slice(&file_size.to_le_bytes());
    wav.extend_from_slice(b"WAVE");

    // fmt chunk
    wav.extend_from_slice(b"fmt ");
    wav.extend_from_slice(&16u32.to_le_bytes()); // chunk size
    wav.extend_from_slice(&1u16.to_le_bytes());  // PCM format
    wav.extend_from_slice(&1u16.to_le_bytes());  // mono
    wav.extend_from_slice(&sample_rate.to_le_bytes());
    wav.extend_from_slice(&(sample_rate * 2).to_le_bytes()); // byte rate
    wav.extend_from_slice(&2u16.to_le_bytes());  // block align
    wav.extend_from_slice(&16u16.to_le_bytes()); // bits per sample

    // data chunk
    wav.extend_from_slice(b"data");
    wav.extend_from_slice(&data_size.to_le_bytes());
    for &s in samples {
        wav.extend_from_slice(&s.to_le_bytes());
    }

    wav
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_move_wav_generates_valid_data() {
        let wav = generate_move_wav();
        assert!(wav.len() > 44, "WAV should have header + data");
        assert_eq!(&wav[0..4], b"RIFF");
        assert_eq!(&wav[8..12], b"WAVE");
    }

    #[test]
    fn test_capture_wav_generates_valid_data() {
        let wav = generate_capture_wav();
        assert!(wav.len() > 44, "WAV should have header + data");
        assert_eq!(&wav[0..4], b"RIFF");
        assert_eq!(&wav[8..12], b"WAVE");
    }

    #[test]
    fn test_encode_wav_format() {
        let samples = vec![0i16; 100];
        let wav = encode_wav(&samples, 44100);

        // Check RIFF header
        assert_eq!(&wav[0..4], b"RIFF");
        assert_eq!(&wav[8..12], b"WAVE");
        assert_eq!(&wav[12..16], b"fmt ");
        assert_eq!(&wav[36..40], b"data");

        // Check data size
        let data_size = u32::from_le_bytes([wav[40], wav[41], wav[42], wav[43]]);
        assert_eq!(data_size, 200); // 100 samples * 2 bytes
    }
}
